ROOT_PATH = "/AGATE/AMiner"
L = 5
ratio_test = 0.1
ratio_valid = 0.2

all_node_num = 10987
n_expanded = 1036
all_node_num_expanded = all_node_num + n_expanded

adj_shape = (all_node_num, all_node_num * L)
adj_shape_expanded = (all_node_num + n_expanded, (all_node_num + n_expanded) * L)
max_nnz_am = 43588
max_nnz_am_repeat1 = 43588 + 10000
attribute_dim = 9

######################################################################################################################
# MakeSample IO dir
# prediction_num_of_edge
MakeSample_prediction_num_of_edge_InputDir = ROOT_PATH + "/data/graph"
MakeSample_prediction_num_of_edge_OutputDir = ROOT_PATH + "/data/learning_data/prediction_num_of_edge"
# prediction_num_of_node
MakeSample_prediction_num_of_node_InputDir = ROOT_PATH + "/data/graph"
MakeSample_prediction_num_of_node_OutputDir = ROOT_PATH + "/data/learning_data/prediction_num_of_node"
# link_prediction_appeared
MakeSample_link_prediction_appeared_InputDir = ROOT_PATH + "/data/graph"
MakeSample_link_prediction_appeared_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_appeared"
# link_prediction_disappeared
MakeSample_link_prediction_disappeared_InputDir = ROOT_PATH + "/data/graph"
MakeSample_link_prediction_disappeared_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_disappeared"
# node_prediction_lost
MakeSample_node_prediction_lost_InputDir = ROOT_PATH + "/data/graph"
MakeSample_node_prediction_lost_OutputDir = ROOT_PATH + "/data/learning_data/node_prediction_lost"
# attribute_prediction_new
MakeSample_attribute_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_attribute_prediction_new_OutputDir = ROOT_PATH + "/data/learning_data/attribute_prediction_new"
# attribute_prediction_new_PROSER
MakeSample_attribute_prediction_new_PROSER_InputDir = ROOT_PATH + "/data/graph"
MakeSample_attribute_prediction_new_PROSER_OutputDir = ROOT_PATH + "/data/learning_data/attribute_prediction_new_PROSER"
# link_prediction_new
MakeSample_link_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_link_prediction_new_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_new"
MakeSample_link_prediction_new_Baseline_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_new/Baseline"
MakeSample_link_prediction_new_DeepMatchMax_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_new/DeepMatchMax"
MakeSample_link_prediction_new_FNN_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_new/FNN"
MakeSample_link_prediction_new_PROSER_OutputDir = ROOT_PATH + "/data/learning_data/link_prediction_new/PROSER"

# repeat1_link_prediction_new
MakeSample_repeat1_link_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_repeat1_link_prediction_new_utilize_existing_attribute_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_utilize_existing_attribute"
MakeSample_repeat1_link_prediction_new_utilize_lost_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_utilize_lost"
MakeSample_repeat1_link_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_utilize_new_attribute_link"
MakeSample_repeat1_link_prediction_new_utilize_disappeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_utilize_disappeared"
MakeSample_repeat1_link_prediction_new_utilize_appeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_utilize_appeared"

# repeat1_attribute_prediction_new
MakeSample_repeat1_attribute_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_repeat1_attribute_prediction_new_utilize_existing_attribute_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_attribute_prediction_new_utilize_existing_attribute"
MakeSample_repeat1_attribute_prediction_new_utilize_lost_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_attribute_prediction_new_utilize_lost"
MakeSample_repeat1_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_attribute_prediction_new_utilize_new_attribute_link"
MakeSample_repeat1_attribute_prediction_new_utilize_disappeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_attribute_prediction_new_utilize_disappeared"
MakeSample_repeat1_attribute_prediction_new_utilize_appeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_attribute_prediction_new_utilize_appeared"

MakeSample_repeat1_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/learning_data/repeat1_link_prediction_new_AGATE"

# repeat2_attribute_prediction_new
MakeSample_repeat2_attribute_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_repeat2_attribute_prediction_new_utilize_existing_attribute_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_attribute_prediction_new_utilize_existing_attribute"
MakeSample_repeat2_attribute_prediction_new_utilize_lost_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_attribute_prediction_new_utilize_lost"
MakeSample_repeat2_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_attribute_prediction_new_utilize_new_attribute_link"
MakeSample_repeat2_attribute_prediction_new_utilize_disappeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_attribute_prediction_new_utilize_disappeared"
MakeSample_repeat2_attribute_prediction_new_utilize_appeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_attribute_prediction_new_utilize_appeared"

# repeat2_link_prediction_new_AGATE
MakeSample_repeat2_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/learning_data/repeat2_link_prediction_new_AGATE"

# repeat3_attribute_prediction_new
MakeSample_repeat3_attribute_prediction_new_InputDir = ROOT_PATH + "/data/graph"
MakeSample_repeat3_attribute_prediction_new_utilize_existing_attribute_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_attribute_prediction_new_utilize_existing_attribute"
MakeSample_repeat3_attribute_prediction_new_utilize_lost_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_attribute_prediction_new_utilize_lost"
MakeSample_repeat3_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_attribute_prediction_new_utilize_new_attribute_link"
MakeSample_repeat3_attribute_prediction_new_utilize_disappeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_attribute_prediction_new_utilize_disappeared"
MakeSample_repeat3_attribute_prediction_new_utilize_appeared_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_attribute_prediction_new_utilize_appeared"

# repeat3_link_prediction_new_AGATE
MakeSample_repeat3_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/learning_data/repeat3_link_prediction_new_AGATE"

# Model IO dir
# prediction_num_of_edge
# Baseline
Model_prediction_num_of_edge_InputDir = MakeSample_prediction_num_of_edge_OutputDir
Model_prediction_num_of_edge_new_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/new/Baseline"
Model_prediction_num_of_edge_appeared_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/appeared/Baseline"
Model_prediction_num_of_edge_disappeared_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/disappeared/Baseline"
# LSTM
Model_prediction_num_of_edge_InputDir = MakeSample_prediction_num_of_edge_OutputDir
Model_prediction_num_of_edge_new_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/new/LSTM"
Model_prediction_num_of_edge_appeared_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/appeared/LSTM"
Model_prediction_num_of_edge_disappeared_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_edge/disappeared/LSTM"

# prediction_num_of_node
# Baseline
Model_prediction_num_of_node_InputDir = MakeSample_prediction_num_of_node_OutputDir
Model_prediction_num_of_node_new_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_node/new/Baseline"
Model_prediction_num_of_node_lost_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_node/lost/Baseline"
# LSTM
Model_prediction_num_of_node_InputDir = MakeSample_prediction_num_of_node_OutputDir
Model_prediction_num_of_node_new_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_node/new/LSTM"
Model_prediction_num_of_node_lost_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/prediction_num_of_node/lost/LSTM"

# link_prediction_appeared
Model_link_prediction_appeared_InputDir = MakeSample_link_prediction_appeared_OutputDir
Model_link_prediction_appeared_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/Baseline"
Model_link_prediction_appeared_Random_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/Random"
Model_link_prediction_appeared_COSSIMMLP_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/COSSIMMLP"
Model_link_prediction_appeared_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/STGGNN"
Model_link_prediction_appeared_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/EGCNh"
Model_link_prediction_appeared_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/STGCN"
Model_link_prediction_appeared_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/EGCNo"
Model_link_prediction_appeared_GCN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_appeared/GCN"

# link_prediction_disappeared
Model_link_prediction_disappeared_InputDir = MakeSample_link_prediction_disappeared_OutputDir
Model_link_prediction_disappeared_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/Baseline"
Model_link_prediction_disappeared_Random_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/Random"
Model_link_prediction_disappeared_COSSIMMLP_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/COSSIMMLP"
Model_link_prediction_disappeared_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/STGGNN"
Model_link_prediction_disappeared_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/EGCNh"
Model_link_prediction_disappeared_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/STGCN"
Model_link_prediction_disappeared_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/EGCNo"
Model_link_prediction_disappeared_GCN_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_disappeared/GCN"

# node_prediction_lost
Model_node_prediction_lost_InputDir = MakeSample_node_prediction_lost_OutputDir
Model_node_prediction_lost_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/Baseline"
Model_node_prediction_lost_Random_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/Random"
Model_node_prediction_lost_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/LSTM"
Model_node_prediction_lost_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/STGGNN"
Model_node_prediction_lost_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/EGCNh"
Model_node_prediction_lost_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/STGCN"
Model_node_prediction_lost_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/EGCNo"
Model_node_prediction_lost_GCN_OutputDir = ROOT_PATH + "/data/learning_result/node_prediction_lost/GCN"

# attribute_prediction_new
Model_attribute_prediction_new_InputDir = MakeSample_attribute_prediction_new_OutputDir
Model_attribute_prediction_new_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/attribute_prediction_new/Baseline"
Model_attribute_prediction_new_FNN_OutputDir = ROOT_PATH + "/data/learning_result/attribute_prediction_new/FNN"
Model_attribute_prediction_new_DeepMatchMax_OutputDir = ROOT_PATH + "/data/learning_result/attribute_prediction_new/DeepMatchMax"

# attribute_prediction_new_PROSER_oracle
Model_attribute_prediction_new_PROSER_oracle_InputDir = ROOT_PATH + "/data/graph"
Model_attribute_prediction_new_PROSER_oracle_OutputDir = ROOT_PATH + "/data/result/attribute_prediction_new_PROSER_oracle"

# attribute_prediction_new_PROSER
Model_attribute_prediction_new_PROSER_InputDir = MakeSample_attribute_prediction_new_PROSER_OutputDir
Model_attribute_prediction_new_PROSER_FNN_OutputDir = ROOT_PATH + "/data/learning_result/attribute_prediction_new_PROSER/FNN"

# attribute_prediction_new_PROSER_selecter
Model_attribute_prediction_new_PROSER_selecter_InputDir = ROOT_PATH + "/data/graph"
Model_attribute_prediction_new_PROSER_selecter_OutputDir = ROOT_PATH + "/data/learning_result/attribute_prediction_new/PROSER"

# link_prediction_new
Model_link_prediction_new_Baseline_mix_InputDir = MakeSample_link_prediction_new_Baseline_OutputDir + "/mix"
Model_link_prediction_new_Baseline_learning_InputDir = MakeSample_link_prediction_new_Baseline_OutputDir + "/learning"
Model_link_prediction_new_Baseline_inference_InputDir = MakeSample_link_prediction_new_Baseline_OutputDir + "/inference"

Model_link_prediction_new_DeepMatchMax_mix_InputDir = MakeSample_link_prediction_new_DeepMatchMax_OutputDir + "/mix"
Model_link_prediction_new_DeepMatchMax_learning_InputDir = MakeSample_link_prediction_new_DeepMatchMax_OutputDir + "/learning"
Model_link_prediction_new_DeepMatchMax_inference_InputDir = MakeSample_link_prediction_new_DeepMatchMax_OutputDir + "/inference"

Model_link_prediction_new_FNN_mix_InputDir = MakeSample_link_prediction_new_FNN_OutputDir + "/mix"
Model_link_prediction_new_FNN_learning_InputDir = MakeSample_link_prediction_new_FNN_OutputDir + "/learning"
Model_link_prediction_new_FNN_inference_InputDir = MakeSample_link_prediction_new_FNN_OutputDir + "/inference"

Model_link_prediction_new_PROSER_mix_InputDir = MakeSample_link_prediction_new_PROSER_OutputDir + "/mix"
Model_link_prediction_new_PROSER_learning_InputDir = MakeSample_link_prediction_new_PROSER_OutputDir + "/learning"
Model_link_prediction_new_PROSER_inference_InputDir = MakeSample_link_prediction_new_PROSER_OutputDir + "/inference"

Model_link_prediction_new_COSSIMMLP_Baseline_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/Baseline/mix"
Model_link_prediction_new_COSSIMMLP_Baseline_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/Baseline/learning"
Model_link_prediction_new_COSSIMMLP_Baseline_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/Baseline/inference"

Model_link_prediction_new_COSSIMMLP_DeepMatchMax_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/DeepMatchMax/mix"
Model_link_prediction_new_COSSIMMLP_DeepMatchMax_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/DeepMatchMax/learning"
Model_link_prediction_new_COSSIMMLP_DeepMatchMax_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/DeepMatchMax/inference"

Model_link_prediction_new_COSSIMMLP_FNN_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/FNN/mix"
Model_link_prediction_new_COSSIMMLP_FNN_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/FNN/learning"
Model_link_prediction_new_COSSIMMLP_FNN_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/FNN/inference"

Model_link_prediction_new_COSSIMMLP_PROSER_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/PROSER/mix"
Model_link_prediction_new_COSSIMMLP_PROSER_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/PROSER/learning"
Model_link_prediction_new_COSSIMMLP_PROSER_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/COSSIMMLP/PROSER/inference"

Model_link_prediction_new_DEAL_Baseline_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/Baseline/mix"
Model_link_prediction_new_DEAL_Baseline_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/Baseline/learning"
Model_link_prediction_new_DEAL_Baseline_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/Baseline/inference"

Model_link_prediction_new_DEAL_DeepMatchMax_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/DeepMatchMax/mix"
Model_link_prediction_new_DEAL_DeepMatchMax_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/DeepMatchMax/learning"
Model_link_prediction_new_DEAL_DeepMatchMax_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/DeepMatchMax/inference"

Model_link_prediction_new_DEAL_FNN_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/FNN/mix"
Model_link_prediction_new_DEAL_FNN_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/FNN/learning"
Model_link_prediction_new_DEAL_FNN_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/FNN/inference"

Model_link_prediction_new_DEAL_PROSER_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/PROSER/mix"
Model_link_prediction_new_DEAL_PROSER_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/PROSER/learning"
Model_link_prediction_new_DEAL_PROSER_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/DEAL/PROSER/inference"

Model_link_prediction_new_FNN_Baseline_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/Baseline/mix"
Model_link_prediction_new_FNN_Baseline_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/Baseline/learning"
Model_link_prediction_new_FNN_Baseline_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/Baseline/inference"

Model_link_prediction_new_FNN_DeepMatchMax_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/DeepMatchMax/mix"
Model_link_prediction_new_FNN_DeepMatchMax_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/DeepMatchMax/learning"
Model_link_prediction_new_FNN_DeepMatchMax_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/DeepMatchMax/inference"

Model_link_prediction_new_FNN_FNN_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/FNN/mix"
Model_link_prediction_new_FNN_FNN_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/FNN/learning"
Model_link_prediction_new_FNN_FNN_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/FNN/inference"

Model_link_prediction_new_FNN_PROSER_mix_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/PROSER/mix"
Model_link_prediction_new_FNN_PROSER_learning_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/PROSER/learning"
Model_link_prediction_new_FNN_PROSER_inference_OutputDir = ROOT_PATH + "/data/learning_result/link_prediction_new/FNN/PROSER/inference"

# repeat1_link_prediction_new_utilize_new_attribute_link
Model_repeat1_link_prediction_new_utilize_new_attribute_link_InputDir = MakeSample_repeat1_link_prediction_new_utilize_new_attribute_link_OutputDir
# Model_repeat1_link_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = MakeSample_repeat1_link_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Model_repeat1_link_prediction_new_utilize_new_attribute_link_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/Baseline"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_Random_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/Random"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_COSSIMMLP_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/COSSIMMLP"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/STGGNN"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/EGCNh"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/STGCN"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/EGCNo"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_GCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/GCN"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/DynGEM"
Model_repeat1_link_prediction_new_utilize_new_attribute_link_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_utilize_new_attribute_link/LSTM"

# repeat1_attribute_prediction_new_utilize_new_attribute_link
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_InputDir = MakeSample_repeat1_attribute_prediction_new_utilize_new_attribute_link_OutputDir
# Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = MakeSample_repeat1_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/Baseline"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/LSTM"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/STGGNN"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/EGCNh"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/STGCN"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/EGCNo"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/GCN"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/DynGEM"
Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_attribute_prediction_new_utilize_new_attribute_link/FNN"

# repeat1_link_prediction_new_AGATE
Model_repeat1_link_prediction_new_AGATE_InputDir = MakeSample_repeat1_link_prediction_new_AGATE_OutputDir + "/inference"
Model_repeat1_link_prediction_new_COSSIMMLP_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_AGATE/COSSIMMLP/inference"
Model_repeat1_link_prediction_new_FNN_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_AGATE/FNN/inference"
Model_repeat1_link_prediction_new_DEAL_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat1_link_prediction_new_AGATE/DEAL/inference"

# repeat2_attribute_prediction_new_utilize_new_attribute_link
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_InputDir = MakeSample_repeat2_attribute_prediction_new_utilize_new_attribute_link_OutputDir
# Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = MakeSample_repeat2_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/Baseline"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/LSTM"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/STGGNN"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/EGCNh"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/STGCN"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/EGCNo"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/GCN"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/DynGEM"
Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_attribute_prediction_new_utilize_new_attribute_link/FNN"

# repeat2_link_prediction_new_AGATE
Model_repeat2_link_prediction_new_AGATE_InputDir = MakeSample_repeat2_link_prediction_new_AGATE_OutputDir + "/inference"
Model_repeat2_link_prediction_new_COSSIMMLP_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_link_prediction_new_AGATE/COSSIMMLP/inference"
Model_repeat2_link_prediction_new_FNN_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_link_prediction_new_AGATE/FNN/inference"
Model_repeat2_link_prediction_new_DEAL_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat2_link_prediction_new_AGATE/DEAL/inference"

# repeat3_attribute_prediction_new_utilize_new_attribute_link
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_InputDir = MakeSample_repeat3_attribute_prediction_new_utilize_new_attribute_link_OutputDir
# Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = MakeSample_repeat3_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/Baseline"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/LSTM"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/STGGNN"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/EGCNh"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/STGCN"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/EGCNo"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/GCN"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/DynGEM"
Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_attribute_prediction_new_utilize_new_attribute_link/FNN"

# repeat3_link_prediction_new_AGATE
Model_repeat3_link_prediction_new_AGATE_InputDir = MakeSample_repeat3_link_prediction_new_AGATE_OutputDir + "/inference"
Model_repeat3_link_prediction_new_COSSIMMLP_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_link_prediction_new_AGATE/COSSIMMLP/inference"
Model_repeat3_link_prediction_new_FNN_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_link_prediction_new_AGATE/FNN/inference"
Model_repeat3_link_prediction_new_DEAL_AGATE_OutputDir = ROOT_PATH + "/data/learning_result/repeat3_link_prediction_new_AGATE/DEAL/inference"

# Evaluation IO dir
# prediction_num_of_edge
# Baseline
Evaluation_prediction_num_of_edge_new_Baseline_InputDir = Model_prediction_num_of_edge_new_Baseline_OutputDir
Evaluation_prediction_num_of_edge_appeared_Baseline_InputDir = Model_prediction_num_of_edge_appeared_Baseline_OutputDir
Evaluation_prediction_num_of_edge_disappeared_Baseline_InputDir = Model_prediction_num_of_edge_disappeared_Baseline_OutputDir
# LSTM
Evaluation_prediction_num_of_edge_new_LSTM_InputDir = Model_prediction_num_of_edge_new_LSTM_OutputDir
Evaluation_prediction_num_of_edge_appeared_LSTM_InputDir = Model_prediction_num_of_edge_appeared_LSTM_OutputDir
Evaluation_prediction_num_of_edge_disappeared_LSTM_InputDir = Model_prediction_num_of_edge_disappeared_LSTM_OutputDir
Evaluation_prediction_num_of_edge_new_OutputDir = ROOT_PATH + "/data/result/prediction_num_of_edge/new"
Evaluation_prediction_num_of_edge_appeared_OutputDir = ROOT_PATH + "/data/result/prediction_num_of_edge/appeared"
Evaluation_prediction_num_of_edge_disappeared_OutputDir = ROOT_PATH + "/data/result/prediction_num_of_edge/disappeared"

# prediction_num_of_node
# Baseline
Evaluation_prediction_num_of_node_new_Baseline_InputDir = Model_prediction_num_of_node_new_Baseline_OutputDir
Evaluation_prediction_num_of_node_lost_Baseline_InputDir = Model_prediction_num_of_node_lost_Baseline_OutputDir
# LSTM
Evaluation_prediction_num_of_node_new_LSTM_InputDir = Model_prediction_num_of_node_new_LSTM_OutputDir
Evaluation_prediction_num_of_node_lost_LSTM_InputDir = Model_prediction_num_of_node_lost_LSTM_OutputDir
Evaluation_prediction_num_of_node_new_OutputDir = ROOT_PATH + "/data/result/prediction_num_of_node/new"
Evaluation_prediction_num_of_node_lost_OutputDir = ROOT_PATH + "/data/result/prediction_num_of_node/lost"

# link_prediction_appeared
Evaluation_link_prediction_appeared_Baseline_InputDir = Model_link_prediction_appeared_Baseline_OutputDir
Evaluation_link_prediction_appeared_Random_InputDir = Model_link_prediction_appeared_Random_OutputDir
Evaluation_link_prediction_appeared_COSSIMMLP_InputDir = Model_link_prediction_appeared_COSSIMMLP_OutputDir
Evaluation_link_prediction_appeared_STGGNN_InputDir = Model_link_prediction_appeared_STGGNN_OutputDir
Evaluation_link_prediction_appeared_EGCNh_InputDir = Model_link_prediction_appeared_EGCNh_OutputDir
Evaluation_link_prediction_appeared_STGCN_InputDir = Model_link_prediction_appeared_STGCN_OutputDir
Evaluation_link_prediction_appeared_EGCNo_InputDir = Model_link_prediction_appeared_EGCNo_OutputDir
Evaluation_link_prediction_appeared_GCN_InputDir = Model_link_prediction_appeared_GCN_OutputDir
Evaluation_link_prediction_appeared_OutputDir = ROOT_PATH + "/data/result/link_prediction_appeared"

# link_prediction_disappeared
Evaluation_link_prediction_disappeared_Baseline_InputDir = Model_link_prediction_disappeared_Baseline_OutputDir
Evaluation_link_prediction_disappeared_Random_InputDir = Model_link_prediction_disappeared_Random_OutputDir
Evaluation_link_prediction_disappeared_COSSIMMLP_InputDir = Model_link_prediction_disappeared_COSSIMMLP_OutputDir
Evaluation_link_prediction_disappeared_STGGNN_InputDir = Model_link_prediction_disappeared_STGGNN_OutputDir
Evaluation_link_prediction_disappeared_EGCNh_InputDir = Model_link_prediction_disappeared_EGCNh_OutputDir
Evaluation_link_prediction_disappeared_STGCN_InputDir = Model_link_prediction_disappeared_STGCN_OutputDir
Evaluation_link_prediction_disappeared_EGCNo_InputDir = Model_link_prediction_disappeared_EGCNo_OutputDir
Evaluation_link_prediction_disappeared_GCN_InputDir = Model_link_prediction_disappeared_GCN_OutputDir
Evaluation_link_prediction_disappeared_OutputDir = ROOT_PATH + "/data/result/link_prediction_disappeared"

# node_prediction_lost
Evaluation_node_prediction_lost_Baseline_InputDir = Model_node_prediction_lost_Baseline_OutputDir
Evaluation_node_prediction_lost_Random_InputDir = Model_node_prediction_lost_Random_OutputDir
Evaluation_node_prediction_lost_LSTM_InputDir = Model_node_prediction_lost_LSTM_OutputDir
Evaluation_node_prediction_lost_STGGNN_InputDir = Model_node_prediction_lost_STGGNN_OutputDir
Evaluation_node_prediction_lost_EGCNh_InputDir = Model_node_prediction_lost_EGCNh_OutputDir
Evaluation_node_prediction_lost_STGCN_InputDir = Model_node_prediction_lost_STGCN_OutputDir
Evaluation_node_prediction_lost_EGCNo_InputDir = Model_node_prediction_lost_EGCNo_OutputDir
Evaluation_node_prediction_lost_GCN_InputDir = Model_node_prediction_lost_GCN_OutputDir
Evaluation_node_prediction_lost_OutputDir = ROOT_PATH + "/data/result/node_prediction_lost"

# attribute_prediction_new
Evaluation_attribute_prediction_new_Baseline_InputDir = Model_attribute_prediction_new_Baseline_OutputDir
Evaluation_attribute_prediction_new_FNN_InputDir = Model_attribute_prediction_new_FNN_OutputDir
Evaluation_attribute_prediction_new_DeepMatchMax_InputDir = Model_attribute_prediction_new_DeepMatchMax_OutputDir
Evaluation_attribute_prediction_new_PROSER_selecter_InputDir = Model_attribute_prediction_new_PROSER_selecter_OutputDir
Evaluation_attribute_prediction_new_OutputDir = ROOT_PATH + "/data/result/attribute_prediction_new"

# attribute_prediction_new_PROSER
Evaluation_attribute_prediction_new_PROSER_InputDir = ROOT_PATH + "/data/graph"
Evaluation_attribute_prediction_new_PROSER_OutputDir = ROOT_PATH + "/data/result/attribute_prediction_new_PROSER"

# link_prediction_new
Evaluation_link_prediction_new_COSSIMMLP_Baseline_mix_InputDir = Model_link_prediction_new_COSSIMMLP_Baseline_mix_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_Baseline_learning_InputDir = Model_link_prediction_new_COSSIMMLP_Baseline_learning_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_Baseline_inference_InputDir = Model_link_prediction_new_COSSIMMLP_Baseline_inference_OutputDir

Evaluation_link_prediction_new_COSSIMMLP_DeepMatchMax_mix_InputDir = Model_link_prediction_new_COSSIMMLP_DeepMatchMax_mix_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_DeepMatchMax_learning_InputDir = Model_link_prediction_new_COSSIMMLP_DeepMatchMax_learning_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_DeepMatchMax_inference_InputDir = Model_link_prediction_new_COSSIMMLP_DeepMatchMax_inference_OutputDir

Evaluation_link_prediction_new_COSSIMMLP_FNN_mix_InputDir = Model_link_prediction_new_COSSIMMLP_FNN_mix_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_FNN_learning_InputDir = Model_link_prediction_new_COSSIMMLP_FNN_learning_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_FNN_inference_InputDir = Model_link_prediction_new_COSSIMMLP_FNN_inference_OutputDir

Evaluation_link_prediction_new_COSSIMMLP_PROSER_mix_InputDir = Model_link_prediction_new_COSSIMMLP_PROSER_mix_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_PROSER_learning_InputDir = Model_link_prediction_new_COSSIMMLP_PROSER_learning_OutputDir
Evaluation_link_prediction_new_COSSIMMLP_PROSER_inference_InputDir = Model_link_prediction_new_COSSIMMLP_PROSER_inference_OutputDir

Evaluation_link_prediction_new_DEAL_Baseline_inference_InputDir = Model_link_prediction_new_DEAL_Baseline_inference_OutputDir
Evaluation_link_prediction_new_DEAL_FNN_inference_InputDir = Model_link_prediction_new_DEAL_FNN_inference_OutputDir
Evaluation_link_prediction_new_DEAL_DeepMatchMax_inference_InputDir = Model_link_prediction_new_DEAL_DeepMatchMax_inference_OutputDir
Evaluation_link_prediction_new_DEAL_PROSER_inference_InputDir = Model_link_prediction_new_DEAL_PROSER_inference_OutputDir

Evaluation_link_prediction_new_FNN_Baseline_inference_InputDir = Model_link_prediction_new_FNN_Baseline_inference_OutputDir
Evaluation_link_prediction_new_FNN_FNN_inference_InputDir = Model_link_prediction_new_FNN_FNN_inference_OutputDir
Evaluation_link_prediction_new_FNN_DeepMatchMax_inference_InputDir = Model_link_prediction_new_FNN_DeepMatchMax_inference_OutputDir
Evaluation_link_prediction_new_FNN_PROSER_inference_InputDir = Model_link_prediction_new_FNN_PROSER_inference_OutputDir

Evaluation_link_prediction_new_OutputDir = ROOT_PATH + "/data/result/link_prediction_new"

# graph_prediction
Evaluation_graph_prediction_OutputDir = ROOT_PATH + "/data/result/graph_prediction"

# repeat1_link_prediction_new_utilize_new_attribute_link
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_Baseline_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_Baseline_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_Random_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_Random_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_COSSIMMLP_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_COSSIMMLP_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_STGGNN_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNh_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_STGCN_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_STGCN_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNo_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_GCN_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_GCN_OutputDir
# Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_LSTM_InputDir = Model_repeat1_link_prediction_new_utilize_new_attribute_link_LSTM_OutputDir
Evaluation_repeat1_link_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/result/repeat1_link_prediction_new_utilize_new_attribute_link"

# repeat1_attribute_prediction_new_utilize_new_attribute_link
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_Baseline_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_LSTM_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGGNN_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNh_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGCN_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNo_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_GCN_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_FNN_InputDir = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir
Evaluation_repeat1_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/result/repeat1_attribute_prediction_new_utilize_new_attribute_link"

# repeat1_link_prediction_new_AGATE
Evaluation_repeat1_link_prediction_new_AGATE_COSSIMMLP_InputDir = Model_repeat1_link_prediction_new_COSSIMMLP_AGATE_OutputDir
Evaluation_repeat1_link_prediction_new_AGATE_FNN_InputDir = Model_repeat1_link_prediction_new_FNN_AGATE_OutputDir
Evaluation_repeat1_link_prediction_new_AGATE_DEAL_InputDir = Model_repeat1_link_prediction_new_DEAL_AGATE_OutputDir
Evaluation_repeat1_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/result/repeat1_link_prediction_new_AGATE"

# repeat2_attribute_prediction_new_utilize_new_attribute_link
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_Baseline_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_LSTM_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGGNN_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNh_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGCN_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNo_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_GCN_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_FNN_InputDir = Model_repeat2_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir
Evaluation_repeat2_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/result/repeat2_attribute_prediction_new_utilize_new_attribute_link"

# repeat2_link_prediction_new_AGATE
Evaluation_repeat2_link_prediction_new_AGATE_COSSIMMLP_InputDir = Model_repeat2_link_prediction_new_COSSIMMLP_AGATE_OutputDir
Evaluation_repeat2_link_prediction_new_AGATE_FNN_InputDir = Model_repeat2_link_prediction_new_FNN_AGATE_OutputDir
Evaluation_repeat2_link_prediction_new_AGATE_DEAL_InputDir = Model_repeat2_link_prediction_new_DEAL_AGATE_OutputDir
Evaluation_repeat2_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/result/repeat2_link_prediction_new_AGATE"

# repeat3_attribute_prediction_new_utilize_new_attribute_link
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_Baseline_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_Baseline_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_LSTM_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_LSTM_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGGNN_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGGNN_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNh_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNh_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGCN_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_STGCN_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNo_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_EGCNo_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_GCN_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_GCN_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_DynGEM_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_DynGEM_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_FNN_InputDir = Model_repeat3_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir
Evaluation_repeat3_attribute_prediction_new_utilize_new_attribute_link_OutputDir = ROOT_PATH + "/data/result/repeat3_attribute_prediction_new_utilize_new_attribute_link"

# repeat3_link_prediction_new_AGATE
Evaluation_repeat3_link_prediction_new_AGATE_COSSIMMLP_InputDir = Model_repeat3_link_prediction_new_COSSIMMLP_AGATE_OutputDir
Evaluation_repeat3_link_prediction_new_AGATE_FNN_InputDir = Model_repeat3_link_prediction_new_FNN_AGATE_OutputDir
Evaluation_repeat3_link_prediction_new_AGATE_DEAL_InputDir = Model_repeat3_link_prediction_new_DEAL_AGATE_OutputDir
Evaluation_repeat3_link_prediction_new_AGATE_OutputDir = ROOT_PATH + "/data/result/repeat3_link_prediction_new_AGATE"


######################################################################################################################

# prediction_num_of_edge
prediction_num_of_edge_worker = 2
prediction_num_of_edge_batchSize = 1
prediction_num_of_edge_state_dim = 1
prediction_num_of_edge_output_dim = 1
prediction_num_of_edge_init_L = L
prediction_num_of_edge_niter = 1000
prediction_num_of_edge_patience = 100
prediction_num_of_edge_lr = 0.01
prediction_num_of_edge_max_appeared = 0
prediction_num_of_edge_min_appeared = 0
prediction_num_of_edge_max_disappeared = 0
prediction_num_of_edge_min_disappeared = 0
prediction_num_of_edge_max_new = 853
prediction_num_of_edge_min_new = 0

# prediction_num_of_node
prediction_num_of_node_worker = 2
prediction_num_of_node_batchSize = 1
prediction_num_of_node_state_dim = 1
prediction_num_of_node_output_dim = 1
prediction_num_of_node_init_L = L
prediction_num_of_node_niter = 1000
prediction_num_of_node_patience = 100
prediction_num_of_node_lr = 0.01
prediction_num_of_node_max_new = 1036
prediction_num_of_node_min_new = 2
prediction_num_of_node_max_lost = 0
prediction_num_of_node_min_lost = 0

# link_prediction_appeared
link_prediction_appeared_worker = 2
link_prediction_appeared_batchSize = 1
link_prediction_appeared_state_dim = attribute_dim
link_prediction_appeared_annotation_dim = attribute_dim
link_prediction_appeared_output_dim = all_node_num
link_prediction_appeared_init_L = L
link_prediction_appeared_niter = 100
link_prediction_appeared_n_steps = 5
link_prediction_appeared_patience = 10
link_prediction_appeared_lr = 0.01
link_prediction_appeared_egcnh_parameters_feats_per_node = 100
link_prediction_appeared_egcnh_parameters_feats_per_node_min = 100
link_prediction_appeared_egcnh_parameters_feats_per_node_max = 256
link_prediction_appeared_egcnh_parameters_layer_1_feats = 100
link_prediction_appeared_egcnh_parameters_layer_1_feats_min = 10
link_prediction_appeared_egcnh_parameters_layer_1_feats_max = 200
link_prediction_appeared_egcnh_parameters_layer_2_feats = 20
link_prediction_appeared_egcnh_parameters_layer_2_feats_same_as_l1 = True
link_prediction_appeared_egcnh_parameters_k_top_grcu = 200
link_prediction_appeared_egcnh_parameters_num_layers = 2
link_prediction_appeared_egcnh_parameters_lstm_l1_layers = 1
link_prediction_appeared_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
link_prediction_appeared_egcnh_parameters_lstm_l1_feats_min = 10
link_prediction_appeared_egcnh_parameters_lstm_l1_feats_max = 100
link_prediction_appeared_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_appeared_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_appeared_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
link_prediction_appeared_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
link_prediction_appeared_egcnh_parameters_cls_feats_min = 100
link_prediction_appeared_egcnh_parameters_cls_feats_max = 512
link_prediction_appeared_egcno_parameters_feats_per_node = 100
link_prediction_appeared_egcno_parameters_feats_per_node_min = 100
link_prediction_appeared_egcno_parameters_feats_per_node_max = 256
link_prediction_appeared_egcno_parameters_layer_1_feats = 152
link_prediction_appeared_egcno_parameters_layer_1_feats_min = 10
link_prediction_appeared_egcno_parameters_layer_1_feats_max = 200
link_prediction_appeared_egcno_parameters_layer_2_feats = 20
link_prediction_appeared_egcno_parameters_layer_2_feats_same_as_l1 = True
link_prediction_appeared_egcno_parameters_k_top_grcu = 200
link_prediction_appeared_egcno_parameters_num_layers = 2
link_prediction_appeared_egcno_parameters_lstm_l1_layers = 1
link_prediction_appeared_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
link_prediction_appeared_egcno_parameters_lstm_l1_feats_min = 10
link_prediction_appeared_egcno_parameters_lstm_l1_feats_max = 100
link_prediction_appeared_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_appeared_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_appeared_egcno_parameters_lstm_l2_feats_same_as_l1 = True
link_prediction_appeared_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
link_prediction_appeared_egcno_parameters_cls_feats_min = 100
link_prediction_appeared_egcno_parameters_cls_feats_max = 512


# link_prediction_disappeared
link_prediction_disappeared_worker = 2
link_prediction_disappeared_batchSize = 1
link_prediction_disappeared_state_dim = attribute_dim
link_prediction_disappeared_annotation_dim = attribute_dim
link_prediction_disappeared_output_dim = all_node_num
link_prediction_disappeared_init_L = L
link_prediction_disappeared_niter = 100
link_prediction_disappeared_n_steps = 5
link_prediction_disappeared_patience = 10
link_prediction_disappeared_lr = 0.01
link_prediction_disappeared_egcnh_parameters_feats_per_node = 100
link_prediction_disappeared_egcnh_parameters_feats_per_node_min = 100
link_prediction_disappeared_egcnh_parameters_feats_per_node_max = 256
link_prediction_disappeared_egcnh_parameters_layer_1_feats = 100
link_prediction_disappeared_egcnh_parameters_layer_1_feats_min = 10
link_prediction_disappeared_egcnh_parameters_layer_1_feats_max = 200
link_prediction_disappeared_egcnh_parameters_layer_2_feats = 20
link_prediction_disappeared_egcnh_parameters_layer_2_feats_same_as_l1 = True
link_prediction_disappeared_egcnh_parameters_k_top_grcu = 200
link_prediction_disappeared_egcnh_parameters_num_layers = 2
link_prediction_disappeared_egcnh_parameters_lstm_l1_layers = 1
link_prediction_disappeared_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
link_prediction_disappeared_egcnh_parameters_lstm_l1_feats_min = 10
link_prediction_disappeared_egcnh_parameters_lstm_l1_feats_max = 100
link_prediction_disappeared_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_disappeared_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_disappeared_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
link_prediction_disappeared_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
link_prediction_disappeared_egcnh_parameters_cls_feats_min = 100
link_prediction_disappeared_egcnh_parameters_cls_feats_max = 512
link_prediction_disappeared_egcno_parameters_feats_per_node = 100
link_prediction_disappeared_egcno_parameters_feats_per_node_min = 100
link_prediction_disappeared_egcno_parameters_feats_per_node_max = 256
link_prediction_disappeared_egcno_parameters_layer_1_feats = 152
link_prediction_disappeared_egcno_parameters_layer_1_feats_min = 10
link_prediction_disappeared_egcno_parameters_layer_1_feats_max = 200
link_prediction_disappeared_egcno_parameters_layer_2_feats = 20
link_prediction_disappeared_egcno_parameters_layer_2_feats_same_as_l1 = True
link_prediction_disappeared_egcno_parameters_k_top_grcu = 200
link_prediction_disappeared_egcno_parameters_num_layers = 2
link_prediction_disappeared_egcno_parameters_lstm_l1_layers = 1
link_prediction_disappeared_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
link_prediction_disappeared_egcno_parameters_lstm_l1_feats_min = 10
link_prediction_disappeared_egcno_parameters_lstm_l1_feats_max = 100
link_prediction_disappeared_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_disappeared_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
link_prediction_disappeared_egcno_parameters_lstm_l2_feats_same_as_l1 = True
link_prediction_disappeared_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
link_prediction_disappeared_egcno_parameters_cls_feats_min = 100
link_prediction_disappeared_egcno_parameters_cls_feats_max = 512

# node_prediction_lost
node_prediction_lost_worker = 2
node_prediction_lost_batchSize = 1
node_prediction_lost_state_dim = attribute_dim
node_prediction_lost_annotation_dim = attribute_dim
node_prediction_lost_output_dim = 1
node_prediction_lost_init_L = L
node_prediction_lost_niter = 100
node_prediction_lost_n_steps = 5
node_prediction_lost_patience = 10
node_prediction_lost_lr = 0.01
node_prediction_lost_egcnh_parameters_feats_per_node = 100
node_prediction_lost_egcnh_parameters_feats_per_node_min = 100
node_prediction_lost_egcnh_parameters_feats_per_node_max = 256
node_prediction_lost_egcnh_parameters_layer_1_feats = 100
node_prediction_lost_egcnh_parameters_layer_1_feats_min = 10
node_prediction_lost_egcnh_parameters_layer_1_feats_max = 200
node_prediction_lost_egcnh_parameters_layer_2_feats = 20
node_prediction_lost_egcnh_parameters_layer_2_feats_same_as_l1 = True
node_prediction_lost_egcnh_parameters_k_top_grcu = 200
node_prediction_lost_egcnh_parameters_num_layers = 2
node_prediction_lost_egcnh_parameters_lstm_l1_layers = 1
node_prediction_lost_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
node_prediction_lost_egcnh_parameters_lstm_l1_feats_min = 10
node_prediction_lost_egcnh_parameters_lstm_l1_feats_max = 100
node_prediction_lost_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
node_prediction_lost_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
node_prediction_lost_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
node_prediction_lost_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
node_prediction_lost_egcnh_parameters_cls_feats_min = 100
node_prediction_lost_egcnh_parameters_cls_feats_max = 512
node_prediction_lost_egcno_parameters_feats_per_node = 100
node_prediction_lost_egcno_parameters_feats_per_node_min = 100
node_prediction_lost_egcno_parameters_feats_per_node_max = 256
node_prediction_lost_egcno_parameters_layer_1_feats = 152
node_prediction_lost_egcno_parameters_layer_1_feats_min = 10
node_prediction_lost_egcno_parameters_layer_1_feats_max = 200
node_prediction_lost_egcno_parameters_layer_2_feats = 20
node_prediction_lost_egcno_parameters_layer_2_feats_same_as_l1 = True
node_prediction_lost_egcno_parameters_k_top_grcu = 200
node_prediction_lost_egcno_parameters_num_layers = 2
node_prediction_lost_egcno_parameters_lstm_l1_layers = 1
node_prediction_lost_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
node_prediction_lost_egcno_parameters_lstm_l1_feats_min = 10
node_prediction_lost_egcno_parameters_lstm_l1_feats_max = 100
node_prediction_lost_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
node_prediction_lost_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
node_prediction_lost_egcno_parameters_lstm_l2_feats_same_as_l1 = True
node_prediction_lost_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
node_prediction_lost_egcno_parameters_cls_feats_min = 100
node_prediction_lost_egcno_parameters_cls_feats_max = 512

# attribute_prediction_new
attribute_prediction_new_worker = 2
attribute_prediction_new_batchSize = 1
attribute_prediction_new_d0 = attribute_dim
attribute_prediction_new_d1 = 64
attribute_prediction_new_d2 = 128
attribute_prediction_new_d3 = 1024
attribute_prediction_new_d4 = 512
attribute_prediction_new_d5 = 256
attribute_prediction_new_d6 = 128
attribute_prediction_new_init_L = L
attribute_prediction_new_niter = 100
attribute_prediction_new_patience = 10
attribute_prediction_new_lr = 0.01

# attribute_prediction_new_PROSER
attribute_prediction_new_PROSER_worker = 2
attribute_prediction_new_PROSER_batchSize = 1
attribute_prediction_new_PROSER_state_dim = attribute_dim * 2
attribute_prediction_new_PROSER_output_dim = 1
attribute_prediction_new_PROSER_target_idx = 4 # idx of percentile (min, 25, 50, 75, max)
attribute_prediction_new_PROSER_threshold = 0.996503825224748#0.996990278734766 # threshold of max
attribute_prediction_new_PROSER_drop_percentile = 4
attribute_prediction_new_PROSER_init_L = L
attribute_prediction_new_PROSER_niter = 1000
attribute_prediction_new_PROSER_patience = 10
attribute_prediction_new_PROSER_lr = 0.001

# link_prediction_new
link_prediction_new_worker = 0
link_prediction_new_batchSize = 1
link_prediction_new_state_dim = attribute_dim
link_prediction_new_annotation_dim = attribute_dim
link_prediction_new_output_dim = all_node_num + n_expanded
link_prediction_new_init_L = L
link_prediction_new_niter = 1
link_prediction_new_niter_FNN = 100
link_prediction_new_n_steps = 5
link_prediction_new_patience = 3
link_prediction_new_lr = 0.01

# best methods of each components
best_methods = {"n_appeared":"", "p_appeared":"", "n_disappeared":"", "p_disappeared":"", "n_new":"LSTM", "p_new":"DEAL_PROSER_inference", "n_lost":"", "p_lost":""}
best_methods_attribute_new_OutputDir = Model_attribute_prediction_new_PROSER_selecter_OutputDir

# repeat1_link_prediction_new_utilize_new_attribute_link
repeat1_link_prediction_new_utilize_new_attribute_link_worker = 0
repeat1_link_prediction_new_utilize_new_attribute_link_batchSize = 2
repeat1_link_prediction_new_utilize_new_attribute_link_state_dim = attribute_dim
repeat1_link_prediction_new_utilize_new_attribute_link_annotation_dim = attribute_dim
repeat1_link_prediction_new_utilize_new_attribute_link_output_dim = all_node_num + n_expanded
repeat1_link_prediction_new_utilize_new_attribute_link_init_L = L
repeat1_link_prediction_new_utilize_new_attribute_link_niter = 100
repeat1_link_prediction_new_utilize_new_attribute_link_n_steps = 5
repeat1_link_prediction_new_utilize_new_attribute_link_patience = 10
repeat1_link_prediction_new_utilize_new_attribute_link_lr = 0.01
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_min = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_max = 256
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_min = 10
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_max = 200
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats = 20
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats_same_as_l1 = True
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_k_top_grcu = 200
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_num_layers = 2
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_layers = 1
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_min = 10
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_max = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_min = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_max = 512
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_min = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_max = 256
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats = 152
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_min = 10
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_max = 200
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats = 20
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats_same_as_l1 = True
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_k_top_grcu = 200
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_num_layers = 2
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_layers = 1
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_min = 10
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_max = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats_same_as_l1 = True
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_min = 100
repeat1_link_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_max = 512

# repeat1_attribute_prediction_new_utilize_new_attribute_link
repeat1_attribute_prediction_new_utilize_new_attribute_link_worker = 0
repeat1_attribute_prediction_new_utilize_new_attribute_link_batchSize = 2
repeat1_attribute_prediction_new_utilize_new_attribute_link_state_dim = attribute_dim
repeat1_attribute_prediction_new_utilize_new_attribute_link_annotation_dim = attribute_dim
repeat1_attribute_prediction_new_utilize_new_attribute_link_output_dim = attribute_dim
repeat1_attribute_prediction_new_utilize_new_attribute_link_init_L = L
repeat1_attribute_prediction_new_utilize_new_attribute_link_niter = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_n_steps = 5
repeat1_attribute_prediction_new_utilize_new_attribute_link_patience = 10
repeat1_attribute_prediction_new_utilize_new_attribute_link_lr = 0.01
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_min = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_max = 256
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_min = 10
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_max = 200
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats = 20
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats_same_as_l1 = True
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_k_top_grcu = 200
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_num_layers = 2
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_layers = 1
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_min = 10
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_max = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_min = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_max = 512
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_min = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_max = 256
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats = 152
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_min = 10
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_max = 200
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats = 20
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats_same_as_l1 = True
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_k_top_grcu = 200
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_num_layers = 2
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_layers = 1
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_min = 10
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_max = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats_same_as_l1 = True
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_min = 100
repeat1_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_max = 512

# best methods 2 of each components
best_methods2 = {"n_appeared":"", "p_appeared":"", "n_disappeared":"", "p_disappeared":"", "n_new":"LSTM", "p_new":"repeat1_AGATE_DEAL", "n_lost":"", "p_lost":""}
best_methods_attribute_new_OutputDir2 = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir

# repeat2_attribute_prediction_new_utilize_new_attribute_link
repeat2_attribute_prediction_new_utilize_new_attribute_link_worker = 0
repeat2_attribute_prediction_new_utilize_new_attribute_link_batchSize = 2
repeat2_attribute_prediction_new_utilize_new_attribute_link_state_dim = attribute_dim
repeat2_attribute_prediction_new_utilize_new_attribute_link_annotation_dim = attribute_dim
repeat2_attribute_prediction_new_utilize_new_attribute_link_output_dim = attribute_dim
repeat2_attribute_prediction_new_utilize_new_attribute_link_init_L = L
repeat2_attribute_prediction_new_utilize_new_attribute_link_niter = 1000
repeat2_attribute_prediction_new_utilize_new_attribute_link_n_steps = 5
repeat2_attribute_prediction_new_utilize_new_attribute_link_patience = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_lr = 0.01
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_min = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_max = 256
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_min = 10
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_max = 200
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats = 20
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats_same_as_l1 = True
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_k_top_grcu = 200
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_num_layers = 2
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_layers = 1
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_min = 10
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_max = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_min = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_max = 512
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_min = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_max = 256
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats = 152
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_min = 10
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_max = 200
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats = 20
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats_same_as_l1 = True
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_k_top_grcu = 200
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_num_layers = 2
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_layers = 1
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_min = 10
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_max = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats_same_as_l1 = True
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_min = 100
repeat2_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_max = 512

# best methods 3 of each components
best_methods3 = {"n_appeared":"", "p_appeared":"", "n_disappeared":"", "p_disappeared":"", "n_new":"LSTM", "p_new":"repeat1_AGATE_DEAL", "n_lost":"", "p_lost":""}
best_methods_attribute_new_OutputDir3 = Model_repeat1_attribute_prediction_new_utilize_new_attribute_link_FNN_OutputDir

# repeat3_attribute_prediction_new_utilize_new_attribute_link
repeat3_attribute_prediction_new_utilize_new_attribute_link_worker = 0
repeat3_attribute_prediction_new_utilize_new_attribute_link_batchSize = 2
repeat3_attribute_prediction_new_utilize_new_attribute_link_state_dim = attribute_dim
repeat3_attribute_prediction_new_utilize_new_attribute_link_annotation_dim = attribute_dim
repeat3_attribute_prediction_new_utilize_new_attribute_link_output_dim = attribute_dim
repeat3_attribute_prediction_new_utilize_new_attribute_link_init_L = L
repeat3_attribute_prediction_new_utilize_new_attribute_link_niter = 1000
repeat3_attribute_prediction_new_utilize_new_attribute_link_n_steps = 5
repeat3_attribute_prediction_new_utilize_new_attribute_link_patience = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_lr = 0.01
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_min = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_feats_per_node_max = 256
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_min = 10
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_1_feats_max = 200
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats = 20
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_layer_2_feats_same_as_l1 = True
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_k_top_grcu = 200
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_num_layers = 2
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_layers = 1
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats = 100 # only used with sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_min = 10
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l1_feats_max = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_lstm_l2_feats_same_as_l1 = True
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats = 100 # Hidden size of the classifier
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_min = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcnh_parameters_cls_feats_max = 512
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_min = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_feats_per_node_max = 256
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats = 152
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_min = 10
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_1_feats_max = 200
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats = 20
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_layer_2_feats_same_as_l1 = True
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_k_top_grcu = 200
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_num_layers = 2
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_layers = 1
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats = 35 # only used with sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_min = 10
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l1_feats_max = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_layers = 1 # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats = None # only used with both sp_lstm_A_trainer and sp_lstm_B_trainer
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_lstm_l2_feats_same_as_l1 = True
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats = 147 # Hidden size of the classifier
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_min = 100
repeat3_attribute_prediction_new_utilize_new_attribute_link_egcno_parameters_cls_feats_max = 512